# SPDX-License-Identifier: GPL-3.0-only
# Original at https://github.com/tyron12233/CodeAssist/blob/main/.github/workflows/build-apk.yml
# Changes: Minor adjustments, removal of Cancel previous runs step, but every change can be found with a simple diff.

name: Android CI

on:
  push:
    paths:
      - '.github/workflows/android.yml'
      - 'app/**'
      - 'build-logic/**'
      - 'kotlinc/**'
      - 'gradle/**'
      - 'build.gradle'
      - 'gradle.properties'
      - 'gradlew'
      - 'gradlew.bat'
      - 'public-stable-ids.txt'
      - 'settings.gradle'
  pull_request:
    paths:
      - '.github/workflows/android.yml'
      - 'app/**'
      - 'build-logic/**'
      - 'kotlinc/**'
      - 'gradle/**'
      - 'build.gradle'
      - 'gradle.properties'
      - 'gradlew'
      - 'gradlew.bat'
      - 'public-stable-ids.txt'
      - 'settings.gradle'
  workflow_dispatch:
    inputs:
      RUN_OS_VERSON:
        required: true
        description: "Variant OS:"
        type: choice
        default: ubuntu-latest
        options:
          - ubuntu-latest
          - ubuntu-22.04
          - ubuntu-20.04
      job:
        description: 'Variant api:'
        required: true
        type: choice
        default: 'buildMinApi26'
        options:
          - both
          - buildMinApi21
          - buildMinApi26
jobs:
  buildMinApi26:
    if: ${{ github.event.inputs.job == 'buildMinApi26' || github.event.inputs.job == 'both' }}
    name: Build minApi26 debug APK
    runs-on: ${{ github.event.inputs.RUN_OS_VERSON }}
    steps:
      - uses: actions/checkout@v4.1.3
        with:
          fetch-depth: 0
      - name: Upgrading the Wrapper version
        run: | 
             ./gradlew wrapper --gradle-version 8.0-rc-2 --distribution-type all
             ./gradlew wrapper --gradle-version 8.0-rc-2 --distribution-type all
      - name: Verify the checksum of the Wrapper JAR
        run: |
             cd gradle/wrapper
             curl --location --output gradle-wrapper.jar.sha256 \
                  https://services.gradle.org/distributions/gradle-8.0-rc-2-wrapper.jar.sha256
             echo "  gradle-wrapper.jar" >> gradle-wrapper.jar.sha256
             sha256sum --check gradle-wrapper.jar.sha256

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin

      - name: Build debug APK
        uses: gradle/gradle-build-action@v3.3.1
        with:
          arguments: assembleMinApi26Debug
        env:
          CRASH_REPORT_WEBHOOK_URL: ${{ secrets.CRASH_REPORT_WEBHOOK_URL }}

      - name: Upload debug APK
        uses: actions/upload-artifact@v4.3.3
        with:
          name: apk-minApi26-debug
          path: app/build/outputs/apk/minApi26/debug

  buildMinApi21:
    if: ${{ github.event.inputs.job == 'buildMinApi21' || github.event.inputs.job == 'both' }}
    name: Build minApi21 debug APK
    runs-on: ${{ github.event.inputs.RUN_OS_VERSON }}
    steps:
      - uses: actions/checkout@v4.1.3
        with:
          fetch-depth: 0
      - name: Upgrading the Wrapper version
        run: | 
             ./gradlew wrapper --gradle-version 8.0-rc-2 --distribution-type all
             ./gradlew wrapper --gradle-version 8.0-rc-2 --distribution-type all
      - name: Verify the checksum of the Wrapper JAR
        run: |
             cd gradle/wrapper
             curl --location --output gradle-wrapper.jar.sha256 \
                  https://services.gradle.org/distributions/gradle-8.0-rc-2-wrapper.jar.sha256
             echo "  gradle-wrapper.jar" >> gradle-wrapper.jar.sha256
             sha256sum --check gradle-wrapper.jar.sha256

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin

      - name: Build debug APK
        uses: gradle/gradle-build-action@v3.3.1
        with:
          arguments: assembleMinApi21Debug
        env:
          CRASH_REPORT_WEBHOOK_URL: ${{ secrets.CRASH_REPORT_WEBHOOK_URL }}

      - name: Upload debug APK
        uses: actions/upload-artifact@v4.3.3
        with:
          name: apk-minApi21-debug
          path: app/build/outputs/apk/minApi21/debug
